apiVersion: v1
kind: Service
metadata:
  name: productmanagement-service
spec:
  selector:
    app: productmanagement
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8087
    nodePort: 31110